Fix error messages for bos and miner utilities
- redirect error messages to stderr

diff --git a/package/mining/miner_tools/files/miner b/package/mining/miner_tools/files/miner
--- a/package/mining/miner_tools/files/miner
+++ b/package/mining/miner_tools/files/miner
@@ -34,7 +34,7 @@ ip_report() {
 
 fault_light() {
 	if [ $# -ne 1 -o \( "$1" != 'on' -a "$1" != 'off' \) ]; then
-		echo "command 'fault_light' takes only one argument [on|off]"
+		echo "command 'fault_light' takes only one argument [on|off]" >&2
 		exit 1
 	fi
 	if [ $BOS_MODE == 'recovery' ]; then
@@ -58,12 +58,12 @@ nand_install() {
 	local stage1_script="stage1.sh"
 
 	if [ $# -gt 0 ]; then
-		echo "command 'nand_install' does not take any argument"
+		echo "command 'nand_install' does not take any argument" >&2
 		exit 1
 	fi
 
 	if [ ! -f "$firmware_tar" ]; then
-		echo "firmware tarball '$firmware_tar' is missing"
+		echo "firmware tarball '$firmware_tar' is missing" >&2
 		exit 1
 	fi
 
@@ -113,7 +113,7 @@ nand_install() {
 
 # check number of arguments
 if [ $# -lt 1 ]; then
-	echo "missing command argument"
+	echo "missing command argument" >&2
 	exit 1
 fi
 
@@ -129,7 +129,7 @@ case $command in
 		usage
 	;;
 	*)  # unknown command
-		echo "unknown command '$command'"
+		echo "unknown command '$command'" >&2
 		exit 1
 	;;
 esac
diff --git a/package/system/bos_tools/files/bos b/package/system/bos_tools/files/bos
--- a/package/system/bos_tools/files/bos
+++ b/package/system/bos_tools/files/bos
@@ -18,7 +18,7 @@ usage() {
 
 factory_reset() {
 	if [ $# -gt 0 ]; then
-		echo "command 'factory_reset' does not take any argument"
+		echo "command 'factory_reset' does not take any argument" >&2
 		exit 1
 	fi
 	# erase U-Boot environment
@@ -30,13 +30,13 @@ factory_reset() {
 run_recovery() {
 	set +e
 	if [ $# -gt 0 ]; then
-		echo "command 'run_recovery' does not take any argument"
+		echo "command 'run_recovery' does not take any argument" >&2
 		exit 1
 	fi
 	# check if uboot_env partition is not corrupted
 	if [ -n "$(fw_printenv 2>&1 >/dev/null)" ]; then
-		echo "U-Boot environment is corrupted and recovery mode cannot be run"
-		echo "Factory reset can fix this issue"
+		echo "U-Boot environment is corrupted and recovery mode cannot be run" >&2
+		echo "Factory reset can fix this issue" >&2
 		exit 1
 	fi
 	if [ $(uci get network.lan.proto) == 'static' ]; then
@@ -68,7 +68,7 @@ run_recovery() {
 
 ip_report() {
 	if [ $# -gt 0 ]; then
-		echo "command 'ip_report' does not take any argument"
+		echo "command 'ip_report' does not take any argument" >&2
 		exit 1
 	fi
 	# check if it is enabled in configuration
@@ -88,7 +88,7 @@ ip_report() {
 
 # check number of arguments
 if [ $# -lt 1 ]; then
-	echo "missing command argument"
+	echo "missing command argument" >&2
 	exit 1
 fi
 
@@ -104,7 +104,7 @@ case $command in
 		usage
 	;;
 	*)  # unknown command
-		echo "unknown command '$command'"
+		echo "unknown command '$command'" >&2
 		exit 1
 	;;
 esac
